/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import GrafosPkg.Grafo;
import javax.swing.JComboBox;

/**
 *
 * @author linda
 */
public class InterGraf extends javax.swing.JFrame {
private final Grafo graf;
    
    
    /**
     * Creates new form InterGraf
     */
    public InterGraf() {
        graf= new Grafo("Jutiapa-AsuncionMita-Jalpatagua-ElProgreso-Moyuta-Quesada-Zapotitlan-Atescatempa-AguaBlanca-ElAdelanto-Comapa-SantaCatarinaMita-Conguaco-Yupiltepeque-Jerez-Pasaco-SanJoseAcatempa");
        initComponents();
        LlenarComboBox(INICIO);
        LlenarComboBox(FIN);
        CrearRutas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        INICIO = new javax.swing.JComboBox<>();
        FIN = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        LblResul = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 204, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.black);

        INICIO.setBackground(new java.awt.Color(255, 102, 102));
        INICIO.setForeground(new java.awt.Color(0, 0, 102));
        INICIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });

        FIN.setBackground(new java.awt.Color(255, 102, 102));
        FIN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LblResul.setBackground(new java.awt.Color(255, 255, 255));
        LblResul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblResul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblResul.setText("MOSTRARÁ LA RUTA");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("INICIO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("FIN:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(FIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblResul, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INICIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(LblResul, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    String inicio = INICIO.getSelectedItem().toString().trim();
        String fin    = FIN.getSelectedItem().toString().trim();
        String respuesta = graf.encontrarRutaMinimaDijkstra(inicio, fin);
        LblResul.setText(respuesta);   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_INICIOActionPerformed

    private void LlenarComboBox(JComboBox combo){
        combo.removeAllItems();
         combo.addItem("Yupiltepeque");
        combo.addItem("Jerez");
        combo.addItem("Pasaco");
        combo.addItem("ElAdelanto");
        combo.addItem("SanJoseAcatempa");
        combo.addItem("Jutiapa");
        combo.addItem("AsuncionMita");
        combo.addItem("Comapa");
        combo.addItem("SantaCatarinaMita");
        combo.addItem("Conguaco");
        combo.addItem("Quesada");
        combo.addItem("Zapotitlan");
        combo.addItem("Atescatempa");
        combo.addItem("AguaBlanca");
        combo.addItem("Jalpatagua");
        combo.addItem("ElProgreso");
        combo.addItem("Moyuta");
    }
    
    private void CrearRutas(){
         graf.agregarRuta("Yupiltepeque","Jerez", 16);
        graf.agregarRuta("AsuncionMita","AguaBlanca", 28);
        graf.agregarRuta("AsuncionMita","SantaCatarinaMita", 17);
        graf.agregarRuta("AsuncionMita","Jutiapa",32);
        graf.agregarRuta("AsuncionMita","Yupiltepeque", 20);
        graf.agregarRuta("Jalpatagua","Comapa", 17);
        graf.agregarRuta("Jalpatagua","Conguaco", 21);
        graf.agregarRuta("Jalpatagua","Moyuta", 22);
        graf.agregarRuta("Yupiltepeque","ElAdelanto", 8);
        graf.agregarRuta("Yupiltepeque","Atescatempa", 15);
        graf.agregarRuta("Yupiltepeque","Zapotitlan", 10); 
        graf.agregarRuta("Jutiapa","ElAdelanto", 31);
        graf.agregarRuta("Jutiapa","Comapa", 43);
        graf.agregarRuta("Jutiapa","Jalpatagua", 41);
        graf.agregarRuta("Jutiapa","Quesada", 21);
        graf.agregarRuta("Quesada","SanJoseAcatempa", 21);
        graf.agregarRuta("SanJoseAcatempa","Jalpatagua", 35);
        graf.agregarRuta("Jalpatagua","Quesada", 25);
        graf.agregarRuta("AsuncionMita","Atescatempa", 30);
        graf.agregarRuta("AguaBlanca","SantaCatarinaMita", 17);
        graf.agregarRuta("SantaCatarinaMita","ElProgreso", 20);
        graf.agregarRuta("SantaCatarinaMita","Jutiapa", 45);
        graf.agregarRuta("Jutiapa","Yupiltepeque", 23);
        graf.agregarRuta("Jutiapa","ElProgreso", 15);
        graf.agregarRuta("Atescatempa","Jerez", 12); 
        graf.agregarRuta("Jerez","Zapotitlan", 18); 
        graf.agregarRuta("Zapotitlan","ElAdelanto", 5);
        graf.agregarRuta("Zapotitlan","Comapa", 74); 
        graf.agregarRuta("ElAdelanto","Comapa", 68); 
        graf.agregarRuta("Conguaco","Moyuta", 7); 
        graf.agregarRuta("Moyuta","Pasaco", 42);
                

        
        
    }
    /**Set
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*  the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterGraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterGraf().setVisible(true);
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FIN;
    private javax.swing.JComboBox<String> INICIO;
    private javax.swing.JLabel LblResul;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
